#
# * created by moraisandreua
#

#
# * it's highly recommended server sided requests to protect token's identity
#

#
# * this token is default, use something like https://passwordsgenerator.net/sha512-hash-generator/ to generate another token
#

#
# * don't forget reloading the plugin after changing accessToken
#

#
# * websocket's port is 4567
#

accessToken: 'B109F3BBBC244EB82441917ED06D618B9008DD09B3BEFD1B5E07394C706A8BB980B1D7785E5976EC049B46DF5F1326AF5A2EA6D103FD07C95385FFAB0CACBC86'